spring.application.name=hospitalManagement

spring.datasource.url=jdbc:mysql://localhost:3306/hospitaldb
spring.datasource.username=root
spring.datasource.password=2401301024
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

spring.security.oauth2.client.registration.google.client-id=88515558032-jfkobul5n7akjr86tq796v77dtghqn72.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=****CoCK
spring.security.oauth2.client.registration.google.scope=email,profile
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=priyanshjais123@gmail.com
spring.mail.password=uhad biuz jshr eunw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
jwt.secretKey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7y